### ISSUE TITLE
Loading children module

### ISSUE THREAD

**Issue by cleverjack** [cleverjack/modtools-language-tasks#7]
Hello everyone!
I have problem when I load child module in Angular.
Could you kindly let me know if you know about that?

**Comment by happyguydev** [comment]
Hello @cleverjack !
You can load children's modules this way.
Please consider this code base.

const routes: Routes = [
  {
    path: '...',
    loadChildren: () => import('./pages/CHILDRENMODULENAME.module').then(m => m.FilterQualityModule),
    data: { ... }
  },
  ...
];
